language: node_js
node_js:
- node
cache: npm

stages:
  - eslint
  - lock-lint
  - test

jobs:
  include:
    - stage: eslint
      name: "eslint check"
      script: npm run eslint
    - stage: lock-lint
      name: "lock-lint check"
      script: npm run lock-lint
    - stage: test
      name: "Unit tests"
      script: npm run test